### ISSUE TITLE
Action LSTM Implementation

### ISSUE THREAD

**Issue by zhefan** [nv-tlabs/GameGAN_code#2]
Very cool work!

I have a question regarding the action LSTM implementation (https://github.com/nv-tlabs/GameGAN_code/blob/7e2939563afbbd48d85b1f85828967910bd61fd8/simulator_model/dynamics_engine.py#L65):
Should it be `g_t = tmp[:, 2 * self.hidden_size : 3 * self.hidden_size].tanh()` instead? 

Thanks!

**Comment by seung-kim** [comment]
Oops, yes it should be. Thanks!
